services:
  app:
#    image: LuzAramburo/cbz-tool:latest # TODO: replace when it's ready
    build: .        # TODO: remove. Builds from local Dockerfile instead of pulling image
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/data   # persist any data
    environment:
      - MAX_FILE_SIZE_MB=40  # default is 50; change to override the upload limit
    restart: unless-stopped

volumes:
  app-data: