/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server configuration */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all books */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a CBZ file */
        post: operations["uploadBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge two or more books into a new book */
        post: operations["mergeBooks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get book details */
        get: operations["getBook"];
        put?: never;
        post?: never;
        /** Delete a book */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get book status */
        get: operations["getBookStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the book as a CBZ file */
        get: operations["downloadBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/page/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a page image */
        get: operations["getPage"];
        put?: never;
        post?: never;
        /** Delete a page */
        delete: operations["deletePage"];
        options?: never;
        head?: never;
        /** Move a page to a new position */
        patch: operations["movePage"];
        trace?: never;
    };
    "/api/books/{bookId}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add pages to a book */
        post: operations["addPages"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{bookId}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace all metadata */
        patch: operations["replaceMetadata"];
        trace?: never;
    };
    "/api/books/{bookId}/metadata/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set a single metadata key */
        put: operations["setMetadataKey"];
        post?: never;
        /** Remove a single metadata key */
        delete: operations["deleteMetadataKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Config: {
            /** @description Maximum upload file size in megabytes */
            maxFileSizeMb: number;
        };
        BookSummary: {
            bookId: string;
            title: string | null;
            series: string | null;
            number: string | null;
            pageCount: number;
            coverPageIndex: number;
        };
        PageInfo: {
            index: number;
            filename: string;
        };
        /** @description Arbitrary key/value pairs from ComicInfo.xml (e.g. title, series, number, summary) */
        BookMetadata: {
            [key: string]: string;
        };
        UploadResponse: {
            bookId: string;
            pageCount: number;
            pages: components["schemas"]["PageInfo"][];
            metadata: components["schemas"]["BookMetadata"] | null;
        };
        PageListResponse: {
            pageCount: number;
            pages: components["schemas"]["PageInfo"][];
        };
        MetadataResponse: {
            metadata: components["schemas"]["BookMetadata"] | null;
        };
        BookStatus: {
            /** @example ready */
            status: string;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Unique book identifier */
        bookId: string;
        /** @description Zero-based page index */
        pageIndex: number;
        /** @description Metadata field name (e.g. title, series, number) */
        metadataKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server configuration values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
        };
    };
    listBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of book summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookSummary"][];
                };
            };
        };
    };
    uploadBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The .cbz file to upload
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Book parsed and saved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description No file provided or failed to parse CBZ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description File exceeds the configured size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mergeBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Ordered list of book IDs to merge */
                    bookIds: string[];
                    /** @description Optional metadata for the merged book. Omit to inherit from the first book. */
                    metadata?: components["schemas"]["BookMetadata"] | null;
                };
            };
        };
        responses: {
            /** @description Books merged successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description One or more books not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBookStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookStatus"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    downloadBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CBZ archive file */
            200: {
                headers: {
                    /** @description attachment; filename="Series #N - Title.cbz" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
                /** @description Zero-based page index */
                index: components["parameters"]["pageIndex"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            /** @description Book or page not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deletePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
                /** @description Zero-based page index */
                index: components["parameters"]["pageIndex"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page deleted; updated page list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
            /** @description Book or page not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    movePage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
                /** @description Zero-based page index */
                index: components["parameters"]["pageIndex"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Destination index (0-based) */
                    toIndex: number;
                };
            };
        };
        responses: {
            /** @description Page moved; updated page list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
            /** @description Index out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Image files to add (jpg/png/webp) */
                    files: string[];
                    /** @description Position to insert at (default appends to end) */
                    insertAt?: number;
                };
            };
        };
        responses: {
            /** @description Pages added; updated page list returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
            /** @description No files provided, unsupported file type, or insertAt out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    replaceMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    metadata: components["schemas"]["BookMetadata"] | null;
                };
            };
        };
        responses: {
            /** @description Metadata replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
            /** @description Invalid metadata value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setMetadataKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
                /** @description Metadata field name (e.g. title, series, number) */
                key: components["parameters"]["metadataKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description Metadata key set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
            /** @description value is not a string */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteMetadataKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique book identifier */
                bookId: components["parameters"]["bookId"];
                /** @description Metadata field name (e.g. title, series, number) */
                key: components["parameters"]["metadataKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata key removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
